#pragma once

#define IDD_SETTINGS                    101
#define IDD_RESULT                      102
#define IDD_RESULT_SECTIONS             103
#define IDD_PROGRESS                    104
#define IDD_BUSY                        105
#define IDD_CONFIRM                     106
#define IDD_ATTACHWARN                  107
#define IDC_APIKEY                      1001
#define IDC_MODEL                       1002
#define IDC_SENTFOLDER_LABEL            1003
#define IDC_REGISTER_SENTFOLDER         1004
#define IDC_LEARN_STYLE                 1005
#define IDC_RESULT_TEXT                 1006
#define IDC_TEST_SEND                   1007
#define IDC_TEST_RESULT                 1008
#define IDC_REPLY_BTN                   1009
#define IDC_FORWARD_BTN                 1010
#define IDC_SUMMARIZE_CACHE_MINUTES     1011
#define IDC_CLEAR_SUMMARIZE_CACHE       1012
#define IDC_TRANSLATE_CACHE_MINUTES     1013
#define IDC_CLEAR_TRANSLATE_CACHE       1014
#define IDC_RESULT_PEOPLE               1015
#define IDC_RESULT_SUMMARY              1016
#define IDC_RESULT_ACTION               1017
#define IDC_SENT_FOLDERS                1018
#define IDC_DELETE_PROFILE              1019
#define IDC_UNREGISTER_SELECTED         1020
#define IDC_PROGRESS_TEXT               1021
#define IDC_LEARN_MAX_MAILS             1022
#define IDC_LEARN_MAX_MONTHS            1023
#define IDC_BUSY_TEXT                   1025
#define IDC_CONFIRM_TEXT                1026
#define IDC_CONFIRM_HINT                1027
#define IDC_CONFIRM_REASON              1028
#define IDC_CONFIRM_REASON_LABEL        1029
#define IDC_ATTACH_PHRASE               1030
#define IDC_WARN_MISSING_ATTACHMENT     1031
#define IDC_LICENSE_KEY                 1032
#define IDC_LICENSE_STATUS              1033
#define IDC_LICENSE_REGISTER            1034
